# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIMapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='etfcategory',
            table='ETF_CATEGORY',
        ),
        migrations.AlterModelTable(
            name='etfdata',
            table='ETF_DATA',
        ),
        migrations.AlterModelTable(
            name='etfinfo',
            table='ETF_INFO',
        ),
        migrations.AlterModelTable(
            name='futuresdata',
            table='FUTURES_DATA',
        ),
        migrations.AlterModelTable(
            name='futuresinfo',
            table='FUTURES_INFO',
        ),
        migrations.AlterModelTable(
            name='futuresinvestor',
            table='FUTURES_INVESTOR',
        ),
        migrations.AlterModelTable(
            name='fxdata',
            table='FX_DATA',
        ),
        migrations.AlterModelTable(
            name='fxinfo',
            table='FX_INFO',
        ),
        migrations.AlterModelTable(
            name='indexdata',
            table='INDEX_DATA',
        ),
        migrations.AlterModelTable(
            name='indexinfo',
            table='INDEX_INFO',
        ),
        migrations.AlterModelTable(
            name='irdata',
            table='IR_DATA',
        ),
        migrations.AlterModelTable(
            name='irinfo',
            table='IR_INFO',
        ),
        migrations.AlterModelTable(
            name='stockdata',
            table='STOCK_DATA',
        ),
        migrations.AlterModelTable(
            name='stockdetail',
            table='STOCK_DETAIL',
        ),
        migrations.AlterModelTable(
            name='stockinfo',
            table='STOCK_INFO',
        ),
        migrations.AlterModelTable(
            name='stockinvestor',
            table='STOCK_INVESTOR',
        ),
        migrations.AlterModelTable(
            name='stockshort',
            table='STOCK_SHORT',
        ),
        migrations.AlterModelTable(
            name='stocksuspension',
            table='STOCK_SUSPENSION',
        ),
        migrations.AlterModelTable(
            name='xpathdata',
            table='XPATH_DATA',
        ),
        migrations.AlterModelTable(
            name='xpathinfo',
            table='XPATH_INFO',
        ),
    ]
